USE [master]
GO
/****** Object:  Database [Lesson24]    Script Date: 16.01.2022 19:06:52 ******/
CREATE DATABASE [Lesson24]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lesson24', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\Lesson24.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lesson24_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\Lesson24_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Lesson24] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lesson24].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Lesson24] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Lesson24] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Lesson24] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Lesson24] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Lesson24] SET ARITHABORT OFF 
GO
ALTER DATABASE [Lesson24] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Lesson24] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Lesson24] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Lesson24] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Lesson24] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Lesson24] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Lesson24] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Lesson24] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Lesson24] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Lesson24] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Lesson24] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Lesson24] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Lesson24] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Lesson24] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Lesson24] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Lesson24] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Lesson24] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Lesson24] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Lesson24] SET  MULTI_USER 
GO
ALTER DATABASE [Lesson24] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Lesson24] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Lesson24] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Lesson24] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Lesson24] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Lesson24] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Lesson24] SET QUERY_STORE = OFF
GO
USE [Lesson24]
GO
/****** Object:  Table [dbo].[Departments]    Script Date: 16.01.2022 19:06:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Departments](
	[İd] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[CretedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Departments] PRIMARY KEY CLUSTERED 
(
	[İd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 16.01.2022 19:06:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](20) NOT NULL,
	[LastName] [nvarchar](20) NOT NULL,
	[EmploymentDate] [datetime] NOT NULL,
	[DepartmentId] [int] NOT NULL,
	[ManagerId] [int] NOT NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Departments] ON 
GO
INSERT [dbo].[Departments] ([İd], [Name], [CretedDate]) VALUES (1, N'A', CAST(N'2021-10-10T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Departments] ([İd], [Name], [CretedDate]) VALUES (2, N'B', CAST(N'2021-09-12T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Departments] ([İd], [Name], [CretedDate]) VALUES (3, N'C', CAST(N'2021-12-15T00:00:00.000' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Departments] OFF
GO
SET IDENTITY_INSERT [dbo].[Employees] ON 
GO
INSERT [dbo].[Employees] ([Id], [FirstName], [LastName], [EmploymentDate], [DepartmentId], [ManagerId]) VALUES (1, N'Mamed', N'Mamedov', CAST(N'2021-10-17T00:00:00.000' AS DateTime), 1, 1)
GO
INSERT [dbo].[Employees] ([Id], [FirstName], [LastName], [EmploymentDate], [DepartmentId], [ManagerId]) VALUES (2, N'Akif', N'Aliyev', CAST(N'2021-12-25T00:00:00.000' AS DateTime), 2, 2)
GO
INSERT [dbo].[Employees] ([Id], [FirstName], [LastName], [EmploymentDate], [DepartmentId], [ManagerId]) VALUES (3, N'Ilkin', N'Shahaliyev', CAST(N'2021-03-30T00:00:00.000' AS DateTime), 3, 3)
GO
INSERT [dbo].[Employees] ([Id], [FirstName], [LastName], [EmploymentDate], [DepartmentId], [ManagerId]) VALUES (4, N'Ali', N'Ahmedov', CAST(N'2021-08-22T00:00:00.000' AS DateTime), 4, 4)
GO
SET IDENTITY_INSERT [dbo].[Employees] OFF
GO
ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [FK_Employees_Employees] FOREIGN KEY([Id])
REFERENCES [dbo].[Employees] ([Id])
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [FK_Employees_Employees]
GO
USE [master]
GO
ALTER DATABASE [Lesson24] SET  READ_WRITE 
GO
