USE [master]
GO

/****** Object:  Database [Lesson24]    Script Date: 16.01.2022 13:55:15 ******/
CREATE DATABASE [Lesson24]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lesson24', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\Lesson24.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lesson24_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\Lesson24_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lesson24].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lesson24] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lesson24] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lesson24] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lesson24] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lesson24] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lesson24] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lesson24] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lesson24] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lesson24] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lesson24] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lesson24] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lesson24] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lesson24] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lesson24] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lesson24] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lesson24] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lesson24] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lesson24] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lesson24] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lesson24] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lesson24] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lesson24] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lesson24] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Lesson24] SET  MULTI_USER 
GO

ALTER DATABASE [Lesson24] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lesson24] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lesson24] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lesson24] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Lesson24] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lesson24] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Lesson24] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Lesson24] SET  READ_WRITE 
GO

